### ISSUE TITLE
RangeError: Maximum call stack size exceeded on Shipments page when no Shipments are found

### ISSUE THREAD

**Issue by k2maan** [hotwax/receiving#161] opened 2022-11-08 06:03 UTC
## Current behavior

If the ```No Shipments found``` toast is displayed and you switch to PO or Settings page, ```RangeError: Maximum call stack size exceeded``` is thrown in the console.

## Expected behavior

Call stack error should not be there in the console.

## Steps to reproduce the issue

1. Open the app in mobile view and go to the Shipments page, keeping the sidebar menu and console open.
2. Make sure no shipments are there; hence, the ```No Shipments found``` toast is displayed.
3. From the menu, quickly switch to another page, PO or Settings while the toast is still there.
4. Errors will be visible in the console.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by k2maan** [comment] 2023-01-03 10:10
Not able to replicate the issue now. It might have been solved. @shashwatbangar, @disha1202 can you guys replicate it?

**Comment by k2maan** [comment] 2023-01-09 09:25
Not able to replicate the issue with an Ionic version of < 6.2.

**Comment by k2maan** [comment] 2023-01-10 06:36
Unable to replicate the issue, neither on https://receiving-dev.hotwax.io/purchase-orders nor on my local machine, after updating ESlint dependencies. (OMS- dev-apps, User- hotwax.user). @disha1202, @shashwatbangar please check if you can replicate the issue.

**Comment by disha1202** [comment] 2023-01-11 13:47
> Unable to replicate the issue, neither on https://receiving-dev.hotwax.io/purchase-orders nor on my local machine, after updating ESlint dependencies. (OMS- dev-apps, User- hotwax.user). @disha1202, @shashwatbangar please check if you can replicate the issue.

Unable to replicate the issue on my local.

**Comment by dt2patel** [comment] 2023-02-09 07:51
Closing since it is no longer reproducible.

**Closed** 2023-02-09 07:51 UTC
Labels: bug
